language: python
python:
  - 3.12
# command to install dependencies
# install: "pip install -r requirements.txt"

install:
  - python setup.py install
  - pip install requests python-dateutil pytz

before_script:
 - chmod +x tests/test_client.py

# command to run tests
script: python tests/test_client.py
