services:
  postgres:
    image: postgres:15
    container_name: ocsf_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ocsf_demo
    volumes:
      - ./data:/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - puppy-postgres

  # PuppyGraph
  puppygraph:
    image: puppygraph/puppygraph:1.0-preview
    container_name: puppygraph
    ports:
      - "8081:8081"
      - "8182:8182"
    volumes:
      - ./schema.json:/etc/puppygraph/schema.json
      - ./data:/data
    command: ["--config", "/etc/puppygraph/schema.json"]
    depends_on:
      - postgres
    networks:
      - puppy-postgres

#define the private line
networks:
  puppy-postgres: